FROM node:carbon

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ssr16/package*.json ./

RUN npm install
RUN npm run build
# Bundle app source
COPY ./ssr16 .

EXPOSE 3002
CMD [ "npm", "run", "start:server" ]